
import wx

WIN_TITLE = "HR Management Software"
VMENU_COL_WIDTH = 60
VMENU_COL_COUNT = 2
VMENU_SELECTED_COLOUR = (0xD6, 0xE9, 0xD6)
TERM_HEIGHT = 90
FILE_SAVE = wx.FD_SAVE
FILE_OPEN = wx.FD_OPEN
DIAG_YESNO = wx.YES_NO | wx.YES_DEFAULT | wx.STAY_ON_TOP
DIAG_ERR = wx.ICON_ERROR | wx.STAY_ON_TOP
DIAG_INFO = wx.ICON_INFORMATION | wx.OK | wx.STAY_ON_TOP
